spring:
  application:
    name: pruebacastores
  datasource:
    url: jdbc:mysql://localhost:3306/pruebacastores
    username: root
    password: ""
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  h2:
    console:
      enabled: true
  devtools:
    restart:
      enabled: true